name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - folium=0.6.0
  - ipykernel=4.9.0
  - ipyleaflet=0.9.0
  - ipywidgets=7.4.1
  - jupyter=1.0.0
  - jupyterhub=0.9.2
  - matplotlib=2.2.3
  - nbconvert=5.4.0
  - owslib=0.16.0
  - pandas=0.23.4
  - pip=18.0
  - pytz=2018.5
  - pyyaml=3.13
  - wheel=0.31.1
  - ncurses=6.1
  - numpy=1.15.1
  - pip:
    - astunparse==1.5.0
    - colour==0.1.5
    - geojson==2.4.0
    - markdown==2.6.11
    - mpld3==0.3
    - pixiedust==1.1.11
    - py4j==0.10.6
    - pyspark==2.3.0
    - shapely==1.6.4.post2
    - oauthenticator==0.8.0